// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okfnhoegpnahzezlgfto.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9rZm5ob2VncG5haHplemxnZnRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ3MjY1ODEsImV4cCI6MjA1MDMwMjU4MX0.q2Eyn_V-NY--TWodPjmJCd-spa038Easta8jxr-f8GI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);